# Generated by Django 3.2.9 on 2021-11-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211109_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
