# Generated by Django 3.2.9 on 2021-11-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211116_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
