# Generated by Django 3.2.9 on 2021-11-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211119_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.categoria'),
        ),
    ]
